### ISSUE TITLE
Support draggingDestinationFeedbackStyle .gap

### ISSUE THREAD

**Issue by nickkeets** [thompsonate/NSTableView-Drag-and-Drop#1]
What if I want to set `tableview.draggingDestinationFeedbackStyle = .gap` on the right table view? There seems to be a bug in this case.

**Comment by thompsonate** [comment]
Whoa, I didn't know that existed!

Is the issue when dragging a cell up within the right table view? It seems to work fine when dragging from the left table view.

**Comment by nickkeets** [comment]
I suspect this is a bug with NSTableView itself, but try reordering the rows on the right table to see the bug.

**Comment by thompsonate** [comment]
Just to be clear, is this what you're referring to? Does seem like it could be a NSTableView bug.

![NSTableViewFeedbackStyleGap](https://user-images.githubusercontent.com/11262741/55244794-401f5a00-5218-11e9-9e0f-e5baba689802.gif)

**Comment by nickkeets** [comment]
Yes, that's the bug, sorry for not being clear.

**Comment by thompsonate** [comment]
I figured it out! It's a bug that you can get around by implementing `tableView(_:heightOfRow:)`. Will be updating this and the blog post shortly.

**Comment by nickkeets** [comment]
Nice!! Thanks.
